### ISSUE TITLE
Banner Image?

### ISSUE THREAD

**Issue by samgreco** [backdrop-contrib/uc_clearance#1]
Is there any way to have this add a banner image when an item is on clearance?

**Comment by bugfolder** [comment]
Not currently (without writing some code), but it's an interesting potential feature.

**Comment by samgreco** [comment]
I think it would be.  I had it working in Drupal/UC3 using a conditional.  But it's not working in BD.  But it's a small issue.  Not a show stopper.  But would be a great feature.

**Comment by bugfolder** [comment]
You can do this now, I think. Create a View of nodes with a Block display. Add a filter of whether it has the clearance taxonomy term. You can add extra verbiage by adding a header. If there's no clearance, it will display as empty. You can then add the block to your layouts in the position where you'd like the banner.

**Comment by bugfolder** [comment]
@samgreco, did this work for you?

**Comment by samgreco** [comment]
Sorry.  Haven't gotten to this yet.  It'll probably be a few days before I can get to it.

**Comment by samgreco** [comment]
Just to show what I am trying to achieve:

![product with clearance](https://github.com/backdrop-contrib/uc_clearance/assets/11745646/0fb1599e-ec16-43e3-85f7-29b19b3380e5)

**Comment by bugfolder** [comment]
I think that's all doable with a View.

**Comment by samgreco** [comment]
I thought so too.  But I could not get it to be conditional.  I got the image on all products in the catalog.

**Comment by bugfolder** [comment]
Create a View of Content, then add two filters: one of "Content: Type", that restricts to your Ubercart product type(s), and the second of type "Has taxonomy term" limited to your clearance term. The View edit page should look like this:

![image](https://github.com/backdrop-contrib/uc_clearance/assets/29214084/651301bb-2545-4910-ba74-f5099be84e91)

My own site has a page that shows just Clearance items, and it uses a View to produce it, and it's not unlike what you showed:

![image](https://github.com/backdrop-contrib/uc_clearance/assets/29214084/a74845f8-535b-4849-b8c9-c1a42b4990de)

**Comment by samgreco** [comment]
I understand that part.  I am trying to have a category of product that contains non-clearance and clearance together.  So if someone is looking for a microphone, for instance, they get a listing of all of them, with the ones on clearance only showing the overlay image.

In Drupal 7 I was able to setup a display for products that had the "clearance image" with a condition (I had a checkbox for clearance items, although I probably could have done it with a term).  Haven't been able to recreate that in BD.

And I have facets that can filter down to categories, brand, price.  

The D7 site is at audiosupply.com and the dev BD site is at asi-bd.tbwdev.com if you want to take a look.

And thanks for all of the help.  This isn't a show stopper at this point.  The site is fairly close to going live.

**Comment by bugfolder** [comment]
How about this: In your View, there should be tokens for taxonomy terms (or you can add them by adding taxonomy terms as hidden fields). You could then use those tokens in CSS classes. So if you add another field of custom text for your overlay image, give it a CSS class based on taxonomy terms, then use CSS to selectively show or hide that overlay.

**Comment by samgreco** [comment]
So sorry for not responding to this earlier.  Got side-tracked with with issues.

But you sent me down a path that provided me with a simple solution.  Simple text field doing essentially what you suggested.  I'll cleanup the font, etc.  But this is the solution:

![image](https://github.com/backdrop-contrib/uc_clearance/assets/11745646/b68034e1-88e3-41bf-b602-38a329e4c152)

Again , thanks for pointing me in a direction.

**Comment by bugfolder** [comment]
Looks good, glad to assist. I'll close the issue.
