### ISSUE TITLE
Handle quantity restrictions earlier in the customer interaction

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/uc_clearance#2]
Currently, quantity restrictions are only applied at "review checkout" (if the quantity exceeds available stock, the review is errorered). We should enforce quantity restrictions earlier in the checkout process:

* In the cart (/cart), in response to either Update cart or Checkout, validate quantities.

In addition, some nice fillips to add would be:

* On the product page, if there are options, change the option selection so that user can't choose options that are no longer available.
* In the cart and checkout, if only one product is available, set the  quantity form element to 1 and then disable it, so the only change option is removal.
* Provide a checkbox setting for "All products are clearance" so if a store owner wants all products to behave this way, they don't need to create a separate taxonomy tag for it.
* Make the display of the "Clearance" notice on product pages optional, and consider making that text editable as a setting.

**Comment by bugfolder** [comment]
@richarda78, I've made all the changes above (and then some) to uc_clearance to support more use cases, including (I hope) yours. Would you be in a position to test it? The update is not yet committed to the main branch; you can find it [in this branch](https://github.com/backdrop-contrib/uc_clearance/tree/2_improve_clearance). Note that it runs an update, so it's not easily reversible, but if you can try it out on a dev site, that would be great. Visit the module's settings page; there are several new settings, which I hope will be self-explanatory.

**Comment by richarda78** [comment]
Tested and works as expected, no immediate issues here. Many thanks @bugfolder
